# admin/config.yml

# Configuración del backend (cómo se conecta a tu código)
backend:
  name: git-gateway
  branch: master 
  publish_mode: simple

# Dónde se guardarán las fotos de los productos
media_folder: "img/uploads"
public_folder: "/img/uploads"

# Define las "colecciones" de contenido. En tu caso, solo una: Productos.
collections:
  - name: "productos"
    label: "Productos"
    folder: "_productos"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Nombre del Producto", name: "title", widget: "string" }
      - { label: "Código del Producto", name: "code", widget: "string" }
      - { label: "Imagen Principal", name: "image", widget: "image" }
      - { label: "Imagen para el Hover", name: "image_hover", widget: "image" }
      - { label: "Precio (solo el número)", name: "price", widget: "number" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Hombres", "Mujeres"] }
      - { label: "Tipo de Prenda", name: "type", widget: "select", options: ["Camisa", "Pantalón", "Accesorio", "Blusa", "Gabán", "Otro"] }
      - { label: "Descripción Corta", name: "description", widget: "string" }
      - label: "Tallas Disponibles"
        name: "sizes"
        widget: "list"
        # LA LÍNEA CORREGIDA ES ESTA DE ABAJO. Se añadió name: "size"
        field: { label: "Talla", name: "size", widget: "string" }
       -label: "Colores Disponibles"
        name: "colors"
        widget: "list"
        fields:
          - { label: "Nombre del Color", name: "name", widget: "string" }
          - { label: "Selecciona el Color", name: "hex", widget: "color" }